#!/bin/bash
#
# Build dbconvert standalone binary.
#
# This script:
#   1. Copies dbconvert.cpp into the server source tree
#   2. Applies engine3 patches (required for standalone mode)
#   3. Patches autogenerated readObject() methods
#   4. Adds the CMake target for dbconvert
#   5. Builds the dbconvert binary
#   6. Reverts all engine3 patches (leaves engine3 clean)
#
# The resulting binary is copied to MMOCoreORB/bin/dbconvert.
#
# Usage:
#   ./build.sh <path_to_MMOCoreORB>
#
# Example:
#   ./build.sh /path/to/MMOCoreORB
#
# Prerequisites:
#   - Server source must be fully built (core3 compiles successfully)
#   - engine3 submodule must be clean (no uncommitted changes)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
PATCHES_DIR="$REPO_DIR/patches"

# --- Argument parsing ---

if [ $# -lt 1 ]; then
    echo "Usage: $0 <path_to_MMOCoreORB>"
    echo ""
    echo "Builds the dbconvert standalone database converter."
    echo ""
    echo "Example:"
    echo "  $0 /path/to/MMOCoreORB"
    exit 1
fi

MMOCOREORB="$(cd "$1" && pwd)"
ENGINE3_DIR="$MMOCOREORB/utils/engine3"
SRC_DIR="$MMOCOREORB/src"
BUILD_DIR="$MMOCOREORB/build"
BIN_DIR="$MMOCOREORB/bin"

# --- Validation ---

if [ ! -d "$ENGINE3_DIR" ]; then
    echo "ERROR: engine3 not found at $ENGINE3_DIR"
    exit 1
fi

if [ ! -d "$BUILD_DIR" ]; then
    echo "ERROR: Build directory not found at $BUILD_DIR"
    echo "Run cmake first: cd $BUILD_DIR && cmake .."
    exit 1
fi

if [ ! -f "$SRC_DIR/CMakeLists.txt" ]; then
    echo "ERROR: CMakeLists.txt not found at $SRC_DIR/CMakeLists.txt"
    exit 1
fi

# Check engine3 is clean — patches need a clean tree to apply and revert safely
ENGINE3_STATUS=$(cd "$ENGINE3_DIR" && git status --porcelain 2>/dev/null || true)
if [ -n "$ENGINE3_STATUS" ]; then
    echo ""
    echo "================================================================"
    echo "  engine3 has uncommitted changes — can't patch safely"
    echo "================================================================"
    echo ""
    echo "  dbconvert needs to temporarily patch engine3 and revert when"
    echo "  done. That only works on a clean tree."
    echo ""
    echo "  Dirty files:"
    echo "$ENGINE3_STATUS" | sed 's/^/    /'
    echo ""
    echo "  To fix this, update your engine3 to the latest:"
    echo ""
    echo "    cd $ENGINE3_DIR"
    echo "    git checkout ."
    echo "    git pull"
    echo ""
    echo "  Nobody should be customizing engine3 — if you've forked it,"
    echo "  you'll need to get back in sync with upstream first."
    echo ""
    echo "================================================================"
    exit 1
fi

# Check engine3 is new enough — patches require at least this commit
MIN_ENGINE3_COMMIT="339da044e9cf68e7fd23edf11b3e106e96cfb78d"
MIN_ENGINE3_SHORT="339da044"
ENGINE3_COMMIT=$(cd "$ENGINE3_DIR" && git rev-parse HEAD 2>/dev/null || echo "unknown")
ENGINE3_SHORT=$(cd "$ENGINE3_DIR" && git rev-parse --short HEAD 2>/dev/null || echo "unknown")

if [ "$ENGINE3_COMMIT" = "unknown" ]; then
    echo ""
    echo "================================================================"
    echo "  Can't determine engine3 version"
    echo "================================================================"
    echo ""
    echo "  engine3 doesn't appear to be a git repository."
    echo "  dbconvert needs engine3 at commit $MIN_ENGINE3_SHORT or later."
    echo ""
    echo "================================================================"
    exit 1
fi

# The minimum commit date of 339da044 (2024-02-21). Used as fallback when
# engine3 upstream was rebased and the original commit hash no longer exists
# in the current history.
MIN_ENGINE3_DATE="2024-02-21"

if ! (cd "$ENGINE3_DIR" && git merge-base --is-ancestor "$MIN_ENGINE3_COMMIT" HEAD 2>/dev/null); then
    # Ancestor check failed — commit may not exist if engine3 was rebased.
    # Fall back to comparing HEAD's commit date against the minimum date.
    HEAD_DATE=$(cd "$ENGINE3_DIR" && git log -1 --format='%cs' HEAD 2>/dev/null || echo "")

    if [ -z "$HEAD_DATE" ] || [[ "$HEAD_DATE" < "$MIN_ENGINE3_DATE" ]]; then
        echo ""
        echo "================================================================"
        echo "  engine3 is out of date"
        echo "================================================================"
        echo ""
        echo "  Your engine3 is at:  $ENGINE3_SHORT ($HEAD_DATE)"
        echo "  Minimum required:    $MIN_ENGINE3_SHORT ($MIN_ENGINE3_DATE)"
        echo ""
        echo "  Update it:"
        echo ""
        echo "    cd $ENGINE3_DIR"
        echo "    git pull"
        echo ""
        echo "  Then try building dbconvert again."
        echo ""
        echo "================================================================"
        exit 1
    fi

    echo "  Note: engine3 commit $MIN_ENGINE3_SHORT not in history (upstream may"
    echo "  have been rebased), but HEAD date ($HEAD_DATE) is recent enough."
    echo "  Proceeding."
fi

echo "  engine3 commit: $ENGINE3_SHORT (ok)"

echo "=== Building dbconvert ==="
echo "  MMOCoreORB:  $MMOCOREORB"
echo "  Engine3:     $ENGINE3_DIR"
echo "  Repo:        $REPO_DIR"
echo ""

# Track whether we need cleanup
PATCHES_APPLIED=false
CMAKE_MODIFIED=false
DBCONVERT_COPIED=false

cleanup() {
    echo ""
    echo "--- Cleanup ---"

    if [ "$PATCHES_APPLIED" = true ]; then
        echo "Reverting engine3 patches..."
        (cd "$ENGINE3_DIR" && git checkout -- .) 2>/dev/null || true
        echo "  engine3 restored to clean state"
    fi

    if [ "$CMAKE_MODIFIED" = true ]; then
        echo "Reverting CMakeLists.txt..."
        (cd "$MMOCOREORB" && git checkout -- src/CMakeLists.txt) 2>/dev/null || true
        echo "  CMakeLists.txt restored"
    fi

    if [ "$DBCONVERT_COPIED" = true ] && [ -f "$SRC_DIR/tools/dbconvert.cpp" ]; then
        echo "Removing dbconvert.cpp from source tree..."
        rm -f "$SRC_DIR/tools/dbconvert.cpp"
        rmdir "$SRC_DIR/tools" 2>/dev/null || true
        echo "  dbconvert.cpp removed"
    fi

    # Note: we leave the autogen patches (they get overwritten on next IDL rebuild)
}

# Always clean up on exit
trap cleanup EXIT

# --- Step 1: Copy dbconvert.cpp ---

echo "[1/5] Copying dbconvert.cpp..."
mkdir -p "$SRC_DIR/tools"
cp "$REPO_DIR/src/tools/dbconvert.cpp" "$SRC_DIR/tools/dbconvert.cpp"
DBCONVERT_COPIED=true
echo "  Copied to $SRC_DIR/tools/dbconvert.cpp"

# --- Step 2: Apply engine3 patches ---

echo "[2/5] Applying engine3 patches..."
PATCH_COUNT=0
for patch in "$PATCHES_DIR"/0*.patch; do
    [ -f "$patch" ] || continue
    PATCH_NAME="$(basename "$patch")"
    if (cd "$ENGINE3_DIR" && git apply --check "$patch" 2>/dev/null); then
        (cd "$ENGINE3_DIR" && git apply "$patch")
        echo "  Applied: $PATCH_NAME"
        PATCH_COUNT=$((PATCH_COUNT + 1))
    else
        echo ""
        echo "================================================================"
        echo "  Patch failed: $PATCH_NAME"
        echo "================================================================"
        echo ""
        echo "  This usually means your engine3 is out of date."
        echo ""
        echo "  Update it:"
        echo ""
        echo "    cd $ENGINE3_DIR"
        echo "    git pull"
        echo ""
        echo "  Then try building dbconvert again."
        echo ""
        echo "================================================================"
        exit 1
    fi
done
PATCHES_APPLIED=true
echo "  $PATCH_COUNT patches applied"

# --- Step 3: Patch autogenerated readObject() methods ---

echo "[3/5] Patching autogenerated readObject() methods..."
if [ -f "$REPO_DIR/scripts/patch_autogen.py" ]; then
    python3 "$REPO_DIR/scripts/patch_autogen.py" "$SRC_DIR" 2>&1 | tail -1
else
    echo "  WARNING: patch_autogen.py not found, skipping"
    echo "  Autogen patch is required for correct conversion behavior."
fi

# --- Step 4: Add CMake target ---

echo "[4/5] Adding dbconvert CMake target..."

# Check if dbconvert target already exists
if grep -q "add_executable(dbconvert" "$SRC_DIR/CMakeLists.txt" 2>/dev/null; then
    echo "  dbconvert target already exists in CMakeLists.txt"
else
    # Add dbconvert executable after core3 executable
    # Find the line with add_executable(core3 and add dbconvert after the next blank line
    TMPFILE=$(mktemp)

    # Use a Python one-liner for reliable CMakeLists.txt patching
    python3 -c "
import re, sys

with open('$SRC_DIR/CMakeLists.txt', 'r') as f:
    content = f.read()

# 1. Add executable after core3 executable
exe_pattern = r'(add_executable\(core3 [^\n]+\n)'
exe_replace = r'\1\n# Create dbconvert binary (standalone database converter)\nadd_executable(dbconvert EXCLUDE_FROM_ALL tools/dbconvert.cpp server/ServerCore.cpp \${tre3_sources} \${tre3_headers} \${zone3_sources} \${zone3_headers})\n'
content = re.sub(exe_pattern, exe_replace, content, count=1)

# 2. Add dependencies after core3 dependencies
dep_pattern = r'(add_dependencies\(core3 engine3\))'
dep_replace = r'\1\nadd_dependencies(dbconvert engine3 idlobjects)'
content = re.sub(dep_pattern, dep_replace, content, count=1)

# 3. Add link libraries + copy command at the end (before any trailing whitespace)
link_block = '''
# dbconvert link libraries (same as core3)
target_link_libraries(dbconvert
    \${whole_archive_start}
    db3 conf3 web3 status3 ping3 login3 chat3 core3terrain core3templates core3pathfinding idlobjects
    \${whole_archive_end}
    engine3
    \${Boost_LIBRARIES}
    \${GCCLIBATOMIC_LIBRARY} \${PTHREAD_LIB_LINK} \${MYSQL_LIB}
    \${LUA_LIBRARIES}
    \${DB_LIBRARIES} \${OPENSSL_LIBRARIES}
    \${ZLIB_LIBRARIES} \${CMAKE_DL_LIBS})

if (NOT ENABLE_ASAN AND NOT ENABLE_TSAN AND NOT ENABLE_UBSAN AND JEMALLOC_FOUND AND ENABLE_JEMALLOC_LINK)
    target_link_libraries(dbconvert \${JEMALLOC_LIBRARIES})
endif()

if(ENABLE_MULTITHREADED_LINKER)
    use_gold(dbconvert)
endif(ENABLE_MULTITHREADED_LINKER)

# Copy dbconvert binary to bin/
add_custom_command(
    TARGET dbconvert POST_BUILD
    COMMAND \${CMAKE_COMMAND} -E copy
    \$<TARGET_FILE:dbconvert>
    \${CMAKE_SOURCE_DIR}/bin/)
'''

content = content.rstrip() + '\n' + link_block + '\n'

with open('$SRC_DIR/CMakeLists.txt', 'w') as f:
    f.write(content)

print('  CMakeLists.txt patched successfully')
"
    CMAKE_MODIFIED=true
fi

# --- Step 5: Build ---

echo "[5/5] Building dbconvert..."
echo "  Running: cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo .. && make dbconvert -j$(nproc)"
echo ""

cd "$BUILD_DIR"
cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo .. 2>&1 | tail -3
echo ""
make dbconvert -j$(nproc) 2>&1

echo ""

# Check if binary was created
if [ -f "$BIN_DIR/dbconvert" ]; then
    echo "=== Build successful ==="
    echo "  Binary: $BIN_DIR/dbconvert"
    ls -lh "$BIN_DIR/dbconvert"
    echo ""
    echo "Usage:"
    echo "  cd $BIN_DIR"
    echo "  ./dbconvert all              # classic mode (convert everything)"
    echo "  ./dbconvert all --smart      # smart mode (probe + selective, 90%+ faster)"
    echo "  ./dbconvert clean            # Phase 1 only: reset BDB LSNs"
    echo "  ./dbconvert finalize         # Phase 4 only: checkpoint + cleanup"
else
    echo "ERROR: dbconvert binary not found at $BIN_DIR/dbconvert"
    echo "Check the build output above for errors."
    exit 1
fi
