#!/usr/bin/env python3
"""
Patch all autogenerated readObject() methods to conditionally skip
initializeTransientMembers() when Core::MANAGED_REFERENCE_LOAD is false.

This is needed for the database conversion tool - during conversion,
initializeTransientMembers() corrupts data by loading template values,
resetting fields, and creating components that shouldn't exist.

The pattern in every autogenerated readObject() is:
    stream->setOffset(_currentOffset + _varSize);
    }

    initializeTransientMembers();
}

We replace the initializeTransientMembers() call with:
    if (Core::MANAGED_REFERENCE_LOAD) initializeTransientMembers();
"""

import os
import re
import sys

if len(sys.argv) < 2:
    print(f"Usage: {sys.argv[0]} <path_to_MMOCoreORB/src>")
    print("  Patches all autogenerated readObject() methods in src/autogen/")
    sys.exit(1)

SRC_DIR = sys.argv[1]
AUTOGEN_DIR = os.path.join(SRC_DIR, "autogen")

if not os.path.isdir(AUTOGEN_DIR):
    print(f"ERROR: autogen directory not found at {AUTOGEN_DIR}")
    sys.exit(1)

# Pattern: end of readObject's for loop, followed by initializeTransientMembers()
# This is the ONLY place this exact pattern appears (the POD version doesn't call it)
OLD_PATTERN = """\tstream->setOffset(_currentOffset + _varSize);
\t}

\tinitializeTransientMembers();
}"""

NEW_PATTERN = """\tstream->setOffset(_currentOffset + _varSize);
\t}

\tif (Core::MANAGED_REFERENCE_LOAD) initializeTransientMembers();
}"""

patched = 0
skipped = 0
errors = 0

for root, dirs, files in os.walk(AUTOGEN_DIR):
    for fname in files:
        if not fname.endswith('.cpp'):
            continue
        fpath = os.path.join(root, fname)
        try:
            with open(fpath, 'r') as f:
                content = f.read()
        except Exception as e:
            print(f"  ERROR reading {fpath}: {e}")
            errors += 1
            continue

        if OLD_PATTERN not in content:
            skipped += 1
            continue

        # Count occurrences - should be exactly 1 per file
        count = content.count(OLD_PATTERN)
        new_content = content.replace(OLD_PATTERN, NEW_PATTERN)

        with open(fpath, 'w') as f:
            f.write(new_content)

        patched += 1
        if count > 1:
            print(f"  WARNING: {fname} had {count} matches (all patched)")

print(f"\nDone. Patched: {patched}, Skipped: {skipped}, Errors: {errors}")
